version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      ExternalData_OBJECT_STORES: /home/circleci/.ExternalData
      SIMPLE_ITK_MEMORY_CONSTRAINED_ENVIRONMENT: 1
    steps:
      - checkout

      - restore_cache:
          keys:
            - simpleitk-isbi2018-{{ checksum "python/data/manifest.json" }}
            - simpleitk-isbi2018- #use previous cache when the manifest changes

      - run:
          name: Data setup (if cache is not empty then symbolic link to it)
          command: |
            mkdir -p "${ExternalData_OBJECT_STORES}"
            if [ ! -z "$(ls -A ${ExternalData_OBJECT_STORES})" ]; then
              cp -as /home/circleci/.ExternalData/* python/data
            fi
            python python/downloaddata.py "${ExternalData_OBJECT_STORES}" python/data/manifest.json

      - run:
          name: Setup of Python environment
          command: |
            sudo apt-get update; sudo apt-get install enchant
            sudo pip install virtualenv
            virtualenv ~/sitkpy --no-site-packages
            ~/sitkpy/bin/pip install -r tests/requirements_testing.txt
            ~/sitkpy/bin/jupyter nbextension enable --py --sys-prefix widgetsnbextension

      - run:
          name: Activate environment and run the test
          command: |
            source ~/sitkpy/bin/activate
            ~/sitkpy/bin/pytest -v --tb=short tests/test_notebooks.py::Test_notebooks::test_python_notebook

      - save_cache:
          key: simpleitk-isbi2018-{{ checksum "python/data/manifest.json" }}
          paths: 
            - /home/circleci/.ExternalData

  
